import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar  from "./Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body className={inter.className}><Navbar></Navbar>{children}</body>
      <style>
@import url('https://fonts.googleapis.com/css2?family=Butterfly+Kids&family=Jost:ital,wght@1,900&family=Luckiest+Guy&family=Rubik+Scribble&display=swap')
</style>
    </html>
  );
}
